### ISSUE TITLE
DestroyCtx Command Can Corrupt Context Tree

### ISSUE THREAD

**Issue by sree-revoori1** [chipsalliance/caliptra-dpe#189]
See NCC report, page 21

**Comment by jhand2** [comment]
Mostly fixed by https://github.com/chipsalliance/caliptra-dpe/pull/200

There is still an open portion of this. By calling DestroyContext with `destroy-descendants = false`, Buggy code down the tree can strand nodes and privileged components at the root (like SoC manager) don't have any way to clean up the DPE state without a cold reset. It seems like ideally, SoC manager would always reserve the right to reset some part of the SoC and clean up all their DPE contexts.

The most straightforward mitigation owuld be to force destroy_descendents to always be true. And I think that would be ok in all the use-cases we're aware of. Especially since stranded context can never be re-integrated back into the tree, so I think they may be of minimal value. You also end up in a state where the child thinks it has a parent, but the parent has no record of the child.

**Comment by jhand2** [comment]
Further fix in https://github.com/chipsalliance/caliptra-dpe/pull/232
