### ISSUE TITLE
Fix IssuerAndSerialNumber in CMS Content message

### ISSUE THREAD

**Issue by sree-revoori1** [chipsalliance/caliptra-dpe#280]
From @jhand2: "I looked more into PKCS7 and I do think we are using IssuerAndSerialNumber wrong. The purpose of that field is to identify who signed the CMS message. They way IssuerAndSerialNumber identifies that signer is by (1) who issuer the signer's certificate and (2) what serial number that issuer have to the signer. Because SerialNumbers are supposed to be unique under a given CA.
This is a bit annoying, because now not only does DPE need to know the issuer's name, but it also needs to know the issuer's issuer.

The alternative is we could also use SubjectKeyIdentifier. But this does have the additional constraint that we would be requiring the signer to use the SubjectKeyIdentifier extension in their cert.
"

**Comment by jhand2** [comment]
I guess one datapoint is that the golang PKCS7 library doesn't support SubjectKeyIdentifier. So that isn't a great sign in terms of broad support for using that encoding.

To support this correctly, we would need to add a function to the platforms API for getting the ECA's issuer name. Not the end of the world but it's a bit annoying.

We could add in a comment on the interface that implementations which don't implement the CSR format don't need to implement that platform function (or the one for getting the issuers cert serial number).

**Comment by jhand2** [comment]
Oh, I think the PKCS#7 package doesn't support it because it wasn't added until v3, which isn't technically PKCS#7 (technically CMS is a different RFC).

This library looks like it supports SubjectKeyIdentifier: https://pkg.go.dev/github.com/mastahyeti/cms#SignedData.Verify. And Caliptra does support it as well.

So new idea: we just have one platform function that is responsible for populating the DER-encoded SignerIdentifier. And then it's up to the platform which one they want to use. And still, if a platform doesn't support CSRs, they can just return an error from this platform implementation.
