### ISSUE TITLE
Need to increase MAX_HANDLES to 32 

### ISSUE THREAD

**Issue by fdamato** [chipsalliance/caliptra-dpe#343]
The current implementation of Caliptra DPE Library limit the number of Context Handles to 24. This could be a limiting factor for caliptra integrators.
It has been agreed to increase the number of Context Handles to 32

**Comment by fdamato** [comment]
@jhand2 would you be opposed to move the MAX_HANDLES a build parameter ?

**Comment by jhand2** [comment]
I would be ok with making it a build parameter. Especially since the number might depend on which algorithms are being used or how much DCCM we use. The number might be different for Caliptra 2.0.

The only thing is that we do need to make sure not to exhaust DCCM. So we'll want to make sure the build-time checks in the persistent_data driver handle this.

It might be easiest to have a few options (e.g. 24, 32) and select via a cargo feature.

**Comment by rusty1968** [comment]
caliptrra-dpe alllows for an arbitrary maximum number of handles via cargo feature. We should move this issue to caliptra-sw repo. It is caliptra-runtime that needs to set the desired maximum number of handles.

**Comment by fdamato** [comment]
Based on @rusty1968 comment, filed the issue against Caliptra SW https://github.com/chipsalliance/caliptra-sw/issues/1559
