### ISSUE TITLE
Locality change is not supported in RotateCtxCmd

### ISSUE THREAD

**Issue by yh36** [chipsalliance/caliptra-dpe#350]
In TCG DPE spec, one use case of `RotateContextHandle` is move a context from current locality to another locality. But the implementation in `rotate_context.rs` seems not to support such locality change feature. The `locality` in `fn execute()` is only to specify the current locality that the context handle is bound to. Does it mean that the locality transfer of a context is disallowed in Caliptra DPE?

**Comment by jhand2** [comment]
Yes, this is not supported in Caliptra DPE. This is because during DeriveContext, the locality of the newly created context is saved in Caliptra and is evident in the produced certificate (for each TcbInfo, the locality is included in the vendor_info field). So once a context is created in a locality, we do not want to support moving it to a different locality. Since this may lead to fooling a verifier about which locality is allowed to use the key.
